# Generated by Django 2.1.3 on 2018-11-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181116_0420'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'email'), ('company', 'phone')},
        ),
    ]
